version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main.src.api.app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - KMP_DUPLICATE_LIB_OK=TRUE
      - PYTHONPATH=/app/main:/app
      - OMP_NUM_THREADS=1
      - MKL_NUM_THREADS=1
      - OPENBLAS_NUM_THREADS=1
      - VECLIB_MAXIMUM_THREADS=1
      - NUMEXPR_NUM_THREADS=1
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    command: streamlit run main/src/ui/dashboard.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - KMP_DUPLICATE_LIB_OK=TRUE
      - PYTHONPATH=/app/main:/app
      - OMP_NUM_THREADS=1
      - MKL_NUM_THREADS=1
      - OPENBLAS_NUM_THREADS=1
      - VECLIB_MAXIMUM_THREADS=1
      - NUMEXPR_NUM_THREADS=1
    depends_on:
      - backend
    restart: unless-stopped
